<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\PlanController;

/*
|--------------------------------------------------------------------------
| Api Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

Route::name('api.')
    ->prefix('api')
    ->group(function () {
        Route::post('/login', [AuthController::class, 'login'])->name(
            'api.login'
        );

        Route::middleware('auth:sanctum')->group(function () {
            Route::get('/plans', [PlanController::class, 'index'])->name(
                'plans.index'
            );

            Route::post('/plans', [PlanController::class, 'store'])->name(
                'plans.store'
            );

            Route::get('/plans/{plan}', [PlanController::class, 'show'])->name(
                'plans.show'
            );

            Route::put('/plans/{plan}', [
                PlanController::class,
                'update',
            ])->name('plans.update');

            Route::delete('/plans/{plan}', [
                PlanController::class,
                'destroy',
            ])->name('plans.destroy');
        });
    });
